#!/usr/bin/env python3
# Concept: Mukesh Kesharwani
# Contact: mukesh.kesharwani@adobe.com

"""Write stocks_dashboard/_version.py from current git metadata."""

from __future__ import annotations

import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_URL = "https://github.com/keekar2022/Keekar-s-StocksStatus-Dashboard"
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "stocks_dashboard" / "_version.py"


def _git(*args: str) -> str:
    try:
        out = subprocess.check_output(
            ["git", *args],
            cwd=ROOT,
            stderr=subprocess.DEVNULL,
            text=True,
        )
        return out.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def main() -> int:
    sha_full = _git("rev-parse", "HEAD") or "unknown"
    sha_short = _git("rev-parse", "--short", "HEAD") or sha_full[:7]
    branch = _git("rev-parse", "--abbrev-ref", "HEAD") or "unknown"
    build_time = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    date_part = build_time[:10].replace("-", ".")
    version = f"{date_part}+{sha_short}"
    commit_url = f"{REPO_URL}/commit/{sha_full}" if sha_full != "unknown" else REPO_URL

    content = f'''# Auto-generated by scripts/write_version.py — do not edit by hand.
# Concept: Mukesh Kesharwani
# Contact: mukesh.kesharwani@adobe.com

__version__ = "{version}"
__git_sha__ = "{sha_short}"
__git_sha_full__ = "{sha_full}"
__git_branch__ = "{branch}"
__build_time_utc__ = "{build_time}"
__repo_url__ = "{REPO_URL}"
__commit_url__ = "{commit_url}"
'''
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT} ({version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
